import {motion} from 'framer-motion'
import { db, collection, query, where,doc, getDocs, updateDoc} from "../../firebase/firebase";
import { useNavigate } from 'react-router-dom';
import {
    Dialog,
    DialogContent,
    DialogClose,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
  } from "../ui/dialog"
  import { Button } from "../ui/button"
  import { Label } from '../ui/label'
  import {Input} from '../ui/input'
import { useState,useEffect } from 'react'
import toast from 'react-hot-toast';
 ////FRAMER MOTION VARIANTS
 const cardVariants={
    hidden:{opacity:0,y:50},
    visible:{opacity:1,y:0,transition:{
        delay:.2,
        duration:.9,ease:"easeInOut",
    }
    }
}
const SecondLiveCard = () => {
  const navigate=useNavigate()
  const [username,setusername]=useState<string>('')
  const [value,setValue]=useState('')
  const [loading,setLoading]=useState(false)
  const handleChange=(e:React.ChangeEvent<HTMLInputElement>)=>{
    setValue(e.target.value)
  }
  const saved=localStorage.getItem('username')
useEffect(()=>{
  if(saved){
  setusername(saved)
}
},[])
   ///CHECKING IF NAME EXIST IN FIREBASE FIRST
 const checkIfNameExists = async (generatedRoomCode: number): Promise<boolean> => {
  const usersRef = collection(db, "Rooms");
  const q = query(usersRef, where("roomCode", "==", generatedRoomCode));
  const querySnapshot = await getDocs(q);
  return !querySnapshot.empty; // Returns true if name exists
};
const checkIfQuizHasStarted = async (generatedRoomCode:number): Promise<boolean> => {
  const usersRef = collection(db, "Rooms");
  const q = query(usersRef, where("roomCode", "==", generatedRoomCode),where('quizHasStarted','==',false));
  const querySnapshot = await getDocs(q);
  return !querySnapshot.empty; // Returns true if name exists
};
const updateQuizStatus= async (roomCode:number,data:any)=>{
  const usersRef=collection(db,("Rooms"))
  const q=query(usersRef,where("roomCode","==",roomCode))
  const querySanpshot=await getDocs(q)

  if(!querySanpshot.empty){
    const docRef=doc(db,"Rooms",querySanpshot.docs[0].id)
    await updateDoc(docRef,data)
  }else{
    console.log('eror')
  }

}
const updateScore=async(generatedRoomCode:number)=> {
  const roomCodeExist = await checkIfNameExists(generatedRoomCode);
  const quizHasStarted = await checkIfQuizHasStarted(generatedRoomCode);
  console.log(quizHasStarted)
   try {
    // Check if the ROOM CODE already exists in Firestore

    if (roomCodeExist&&quizHasStarted) {
       await updateQuizStatus(generatedRoomCode,{
        userTwoName:username,
        userTwoOnline:true,
        quizHasStarted:true,
       })
      localStorage.setItem('Roomcode',`${generatedRoomCode}`)
      localStorage.setItem('resultCode',`${generatedRoomCode}`)
      toast.success('WISH YOU LUCK')
      navigate('/livetquiz')
    }else{
      toast.error('SOMEONE HAS ALREADY JOIN PLAYING.... ')
      return;
    }
    // Store the user details in Firestore
  } catch (error: any) {
    console.log(error)
  }

}
  const handleClick=()=>{
    console.log(value)
    if(value!=='')
    {
      console.log(value)
      setLoading(true)
    updateScore(parseInt(value))
    }
    
  }
  return (
    <>
    <Dialog>
<DialogTrigger asChild>
        <motion.div initial='hidden'animate='visible' variants={cardVariants}  className={`mb-6.5 py-7 w-[335px] flex flex-col items-start justify-center md:w-[450px] md:h-[240px] bg-gradient-to-br from-[#a1f2c] to-black/70 z-50 rounded-[6px] md:px-3.5 cursor-pointer `} >

<span className='px-[13px]'>
<h2 className='text-[23px] pb-1 text-white font-semibold md:text-[24px] pt-3 text-center font-dmsans'>Search For Room</h2>
<p className='text-[#f5f5f5cb] text-center text-[15px] font-medium font-dmsans'>Join a quiz room by entering the unique code shared by the host.Find the room and get ready to play.Compete with others and win!</p>

<button className="text-black font-bold mt-4 bg-[#00ff7f] w-[300px] h-10 rounded-lg block mx-auto cursor-pointer">Search Room</button>
</span>

        </motion.div>
        </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Room Code</DialogTitle>
          <DialogDescription className='font-medium text-black'>
            Input Room Code Generated By Your Competitor
          </DialogDescription>
        </DialogHeader>
        <div className="flex items-center space-x-2">
          <div className="grid flex-1 gap-2">
            <Label htmlFor="link" className="sr-only">
              Link
            </Label>
            <Input
              id="link"
              value={value}
              onChange={(e)=>handleChange(e)}
            />
          </div>
        </div>
        <DialogFooter className="sm:justify-start">
          <DialogClose asChild>
            <Button type="button" disabled={loading} onClick={handleClick}>

              {loading?'Searching...' : 'Search'}
            </Button>
          </DialogClose>
        </DialogFooter>
      </DialogContent>
    </Dialog>
    
    
    </>
  )
}

export default SecondLiveCard